### ISSUE TITLE
[Question] Shouldn't stamped messages have a frame id?

### ISSUE THREAD

**Issue by dantenoguera** [aau-cns/mars_ros#3]
Here is a `geometry_msgs/PoseStamped` message I get running an instance of a `gps_node`:

```
header: 
  seq: 12188
  stamp: 
    secs: 1661984306
    nsecs: 715818644
  frame_id: ''
pose: 
  position: 
    x: -0.6634237632091935
    y: 3.4947216960559073
    z: 0.06363313476750493
  orientation: 
    x: -0.005933376892896241
    y: 0.18921987844821742
    z: 0.02400976216308664
    w: 0.9816232291259008
```
(Notice the empty `frame_id`)

Without `frame_id` we can't visualize poses, for example.
